import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Image from "next/image";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("banner btn click");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="banner"
            width={700}
            height={400}
            priority
          />
        </div>
      </main>
    </div>
  );
}
